### ISSUE TITLE
Errors with PGA and RAPU_G attack

### ISSUE THREAD

**Issue by SleepyHC** [CoderWZW/ARLib#12]
Thanks for the efforts and the interesting project. When I try to test PGA and RAPU_G attack on SGL model, I met following errors:

For PGA attack, I met 3 errors:

1. Error: TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0].
https://github.com/CoderWZW/ARLib/blob/edc4cffee4a5b36238725af3bb98bb9f3f812ac5/attack/PGA.py#L46

I tried to change it to `s = torch.tensor(self.interact[self.controlledUser, :].toarray()).cuda()` and met the following error.

2. Error: ValueError: could not broadcast input array from shape (9,1412) into shape (942,1412)
https://github.com/CoderWZW/ARLib/blob/edc4cffee4a5b36238725af3bb98bb9f3f812ac5/attack/PGA.py#L50

I tried to change it to `ui_adj[self.controlledUser, self.userNum:] = np.array(s.cpu())` and met the following error.

3. Error: File "./attack/PGA.py", line 51, in posionDataAttack
    recommender.model._init_uiAdj(ui_adj + ui_adj.T)
  File "./recommend/SGL.py", line 245, in _init_uiAdj
    self.sparse_norm_adj = TorchGraphInterface.convert_sparse_mat_to_tensor(self.sparse_norm_adj).cuda()
  File "./recommend/SGL.py", line 334, in convert_sparse_mat_to_tensor
    coo = X.tocoo()
AttributeError: 'numpy.ndarray' object has no attribute 'tocoo' 

https://github.com/CoderWZW/ARLib/blob/edc4cffee4a5b36238725af3bb98bb9f3f812ac5/attack/PGA.py#L51 
https://github.com/CoderWZW/ARLib/blob/edc4cffee4a5b36238725af3bb98bb9f3f812ac5/recommend/SGL.py#L243-L245
https://github.com/CoderWZW/ARLib/blob/edc4cffee4a5b36238725af3bb98bb9f3f812ac5/recommend/SGL.py#L310-L314

I tried to add a line after https://github.com/CoderWZW/ARLib/blob/edc4cffee4a5b36238725af3bb98bb9f3f812ac5/recommend/SGL.py#L243-L244
` self.sparse_norm_adj = sp.coo_matrix(self.sparse_norm_adj)` but find the training loss called by https://github.com/CoderWZW/ARLib/blob/edc4cffee4a5b36238725af3bb98bb9f3f812ac5/attack/PGA.py#L45 become nan:

> training: 1 batch 0 rec_loss: nan cl_loss nan
training: 1 batch 100 rec_loss: nan cl_loss nan
evaluating the model...
Progress: [++++++++++++++++++++++++++++++++++++++++++++++++++]100%
Quick Ranking Performance  (Top-50 Item Recommendation)
*Current Performance*
Epoch: 1, Hit Ratio:0.11035349004127042 | Precision:0.014352392065344223 | Recall:0.11574197836148567 | NDCG:0.053679494051791274
*Best Performance* 
Epoch: 1, Hit Ratio:0.11035349004127042 | Precision:0.014352392065344223 | Recall:0.11574197836148567 | NDCG:0.053679494051791274
./util/DataLoader.py:77: RuntimeWarning: divide by zero encountered in power
  d_inv = np.power(rowsum, -0.5).flatten()
./util/DataLoader.py:77: RuntimeWarning: divide by zero encountered in power
  d_inv = np.power(rowsum, -0.5).flatten()
training: 2 batch 0 rec_loss: nan cl_loss nan
training: 2 batch 100 rec_loss: nan cl_loss nan
evaluating the model...
Progress: [++++++++++++++++++++++++++++++++++++++++++++++++++]100%

Also, I tried FedRecAttack that also call the `recommender.model._init_uiAdj()` func. It works well without error. So I guess there is something wrong with PGA code but could not find the root for the problem.

For RAPU_G attack, the "higher" module is not included, which confilcts with https://github.com/CoderWZW/ARLib/blob/edc4cffee4a5b36238725af3bb98bb9f3f812ac5/attack/RAPU_G.py#L84

Moreover, I think it would be awsome if you could provide a table of the attack effectiveness of those included attack for reference. In that way, users could have an awareness of whether they are using the repository correctly.

**Comment by CoderWZW** [comment]
We apologize for any inconvenience caused by our recent focus on other projects, which resulted in a temporary lapse in maintaining ARLib. We are pleased to say that your valuable feedback has been thoroughly incorporated, leading to the significant upgrade of ARLib to version 2.0. We wish you continue to share your insightful suggestions. In the near future, we will be releasing a detailed comparison of experimental results.
