### ISSUE TITLE
Some question about random attack

### ISSUE THREAD

**Issue by vickychen928** [CoderWZW/ARLib#14]
Thanks for your repo. It helps me a lot.
I found that you give the item which will be attacked a rating 1.0 in /ARLib/attack/Black/RandomAttack.py.
```python=
def posionDataAttack(self):
        uNum = self.fakeUserNum
        row, col, entries = [], [], []
        for i in range(uNum):
            # fillerItemid = random.sample(set(range(self.itemNum)) - set(self.targetItem),
            #                              self.maliciousFeedbackNum - len(self.targetItem))
            fillerItemid = random.sample(set(range(self.itemNum)) - set(self.targetItem),
                                self.maliciousFeedbackNum)
            row += [i for r in range(len(fillerItemid + self.targetItem))]
            col += fillerItemid + self.targetItem
            entries += [1 for r in range(len(fillerItemid + self.targetItem))]
        fakeRat = csr_matrix((entries, (row, col)), shape=(uNum, self.itemNum), dtype=np.float32)
        return vstack([self.interact, fakeRat])
```
We suppose It means that you give the attacked items at rating = 1.0.

However, I found that you also give all items in raw data at rating = 1.0 in /ARLib/util/DataLoader.py
```python=
def __create_sparse_interaction_matrix(self):
        """
        return a sparse adjacency matrix with the shape (user number, item number)
        """
        row, col, entries = [], [], []
        for pair in self.training_data:
            row += [self.user[pair[0]]]
            col += [self.item[pair[1]]]
            entries += [1.0]
        interaction_mat = sp.csr_matrix((entries, (row, col)), shape=(self.user_num,self.item_num),dtype=np.float32)
        return interaction_mat
```

Hence, our poison train data became this:
<img width="569" alt="image" src="https://github.com/CoderWZW/ARLib/assets/84194000/6a60e258-08ae-4ad4-b32b-44d8c96bed6a">

I'm wondering the reason why you copy the raw data and rewrite it to 1.0 in poison data, but not its original rating. For example in clean/train.txt:
<img width="233" alt="image" src="https://github.com/CoderWZW/ARLib/assets/84194000/56f44684-995f-4e01-84d1-7205561cd08a">

In clean/train.txt, there are various rating like 1, 2, 3, 4, 5. But in poison data, there are only 1.0.
Thanks for your work and your patience. Look forward to your response!

**Comment by CoderWZW** [comment]
Hi, thanks for your question.
As we consider the implicit feedback-based recommender system as default, we pro-process the data from ratings(1, 2, 3, 4, 5) to (0, 1) that represent the user likes/dislikes the item. Thus, the "1" in our code is not the "1" in ratings. Instead, the "1" means a user likes an item.
Any further questions are welcome!

**Comment by vickychen928** [comment]
Thanks for your reply!

I still have some other questions.
1. I'm wondering if there is any difference between popular attacks and unpopular attacks. Because no matter which attack is chosen, it seems that the way to generate poison data is the same in /ARLib/attack/Black/RandomAttack.py.
```
def posionDataAttack(self):
        uNum = self.fakeUserNum
        row, col, entries = [], [], []
        for i in range(uNum):
            # fillerItemid = random.sample(set(range(self.itemNum)) - set(self.targetItem),
            #                              self.maliciousFeedbackNum - len(self.targetItem))
            fillerItemid = random.sample(set(range(self.itemNum)) - set(self.targetItem),
                                self.maliciousFeedbackNum)
            row += [i for r in range(len(fillerItemid + self.targetItem))]
            col += fillerItemid + self.targetItem
            entries += [1 for r in range(len(fillerItemid + self.targetItem))]
        fakeRat = csr_matrix((entries, (row, col)), shape=(uNum, self.itemNum), dtype=np.float32)
        return vstack([self.interact, fakeRat])
```
In the list "entries", it fiils "1" anyway. But in unpopular attack, it should be "0".


2. According to your reply, "0" and "1" represent the user likes or dislikes the item. So if an user doesn't give an item a rating, does it means that this user doesn't like this item?


3. There are two parsers in your code, but when I specify the argument in attack parser like this:
```
python main.py --attackTargetChooseWay popular
```
I got the following information:
<img width="707" alt="image" src="https://github.com/CoderWZW/ARLib/assets/84194000/1be2a6c4-5b87-4935-b430-a56d80a97ad3">

However, it really have this argument in /ARLib/conf/attack_parser.py.
```
    # ===== If attack type is target, the following parameters are necessary ===== #
    parser.add_argument('--attackTargetChooseWay', type=str, default="unpopular", metavar='N',
                        choices=["random", "popular", "unpopular"],
                        help='Target attack selection mode')
```
I would like to know how to use your parser.
Thanks for your work and your patience. Look forward to your response!

**Comment by CoderWZW** [comment]
Hi, 
1. For question 1, I am sorry for your misunderstanding. 
The popular and unpopular in attackTargetChooseWay actually correspond to the target item selection mode. There is no relation with the attack method. 
You might want to implement a nuke attack. However, we merely implement the promotion attack; you have to create a new Python file to implement the new ones. Our ARliB can seamlessly incorporate it.
2. For question 2, if a user doesn't give an item a rating, we are not sure if this user likes this item or not. This is really a research problem to explore. Haha!
3. For question 3, I am not sure what caused the problem now, I will check this problem. Instead, You can directly edit as 

parser.add_argument('--attackTargetChooseWay', type=str, default="unpopular", metavar='N', choices=["random", "popular", "unpopular"], help='Target attack selection mode').

I hope these answers can help you.

**Comment by vickychen928** [comment]
Thanks for your reply!

I have another question.
I'm wondering why the data format is different before and after adding poison data. Just like the example below. The train data fed to the original recommend model is like this:
<img width="443" alt="image" src="https://github.com/CoderWZW/ARLib/assets/84194000/f24eeb96-4f3b-4723-b8dc-e5f25f5c2f0c">

And after generating poison data, the poison data are added to the train data. And the train data fed to the recommend model become like this:
<img width="466" alt="image" src="https://github.com/CoderWZW/ARLib/assets/84194000/7c41fffe-e083-4e6d-8bef-3af319e68139">

I would like to know why the formet of data fed to the recommend model can be different. Shouldn't it be the same?  (我怕用英文說不清楚，是想問在train clean model 的時候，資料形式不一樣(相同的 user-item pair，但是有不同的 score)，為什麼可以做比較？還是其實在 train model 的時候沒有用到 rating 呢？)

Thanks for your work and your patience. Look forward to your response!

**Comment by CoderWZW** [comment]
Hi, 

The raw data did look different. As we pro-process the ratings into 1 directly when we load the data, it is the same format when we train the model no matter whether the data is clean or not (both in the format (1, 0) instead of ratings). 

The related code could be found in line 66, DataLoader.py. 
ratings = np.ones_like(user_np, dtype=np.float32)

Thanks for your question. We welcome any code inquiries, as it could improve our code quality. Haha!

**Comment by vickychen928** [comment]
Thanks for your reply, It hepls me a lots!
