### ISSUE TITLE
About Implementation of CLeaR

### ISSUE THREAD

**Issue by sotaagi** [CoderWZW/ARLib#16]
I tried on several datasets and found out that removing the CW loss and sfa loss entirely from the CLeaR loop leads to minor or non impact on the final poisoning attack performance. Also i'm having trouble reproducing the results from the paper. I am wondering if there's a mistake when implementing the CLeaR method.

**Comment by CoderWZW** [comment]
Hi, thank you for your interest in our work! We have identified some version issues in the published CLeaR code, such as the absence of hyperparameters controlling the balance between CW loss and SFA loss. We will update the code accordingly.

Regarding the reproducibility of experimental results, several factors can influence this, including the selection of the target item, the number of iterations in the bi-level optimization's inner and outer loops and so on. If you use our default parameter settings without adjusting relevant parameters, you may not be able to replicate the results, as the final experimental outcomes are highly dependent on these factors.

We will be updating and organizing all comparison experimental results included in ARLib, including CLeaR, and will provide the corresponding experimental details (such as the selection of target items, various parameter settings, etc.). This update is expected to be completed within the next two months. We hope you continue to follow our work and look forward to the update.
