### ISSUE TITLE
Missing of the poisoning attack evaluation?

### ISSUE THREAD

**Issue by SleepyHC** [CoderWZW/ARLib#7]
Thanks for the code!

I wonder is there are evaluation on the attack result, for example, the recommendation rate for the target item? I have run the code and did not find any output for it.

**Comment by CoderWZW** [comment]
Thank you for your issue！ 
We save and output the results in the file named "log". Four evaluation metrics hit ratio, precision, ndcg and recall are shown in the log. The format is like this :

 ----------Target Attack Test Result Poisoning Environment on Average (Evaluation Metrics @Top-(20))----------
Top 20
HitRate : 0.16593059936908516
Precision : 0.00829652996845426
Recall : 0.03318611987381704
NDCG : 0.01831441867511322

If there are any problems, please contact us!

**Comment by CoderWZW** [comment]
> Thanks for the code!
> 
> I wonder is there are evaluation on the attack result, for example, the recommendation rate for the target item? I have run the code and did not find any output for it.

>
Thank you for your issue！
We save and output the results in the file named "log". Four evaluation metrics hit ratio, precision, ndcg and recall are shown in the log. The format is like this :

----------Target Attack Test Result Poisoning Environment on Average (Evaluation Metrics @Top-(20))----------
Top 20
HitRate : 0.16593059936908516
Precision : 0.00829652996845426
Recall : 0.03318611987381704
NDCG : 0.01831441867511322

If there are any problems, please contact us!

**Comment by SleepyHC** [comment]
Thanks for your help! I've got the point.
